sudo: required
language: java
jdk: oraclejdk8

services:
- docker

env:
  global:
  - secure: Hi8EHWWCH+gcyXBOONECTG+Xj/Qm6oPc3FZ4eF9xm6xK884bqAonUAfvnEzQxOyExwfOFj5YeTyF+5tlNFekD0o7oiQTjoiL0fBrhAipWgIJv6xHH8z0/WQiYTexoBCaM7BMh0GyWFWXGqHsAsflrIXJJIcbOrLMuuW5CB/3bNnVfTopHY9fTMHiDpujySump3TQ1O6gNz1B5yKhD+JY1I2TprylO5zjpYmbwKHLNaozHXBQyr+NpfNYHTP81DEM564yGkSRTQq5RcsMCuEDWpkCNyhlA5VDLFBPB14SotvqMTbEEODeYT68ar70OjTA5swEJ1MDPN2vNnRd1ItGHmApuFoYaI81zEHESwDGYNZ1BmLtXRdVDg7HGJwOqOQS+KPDbI4KdZ6Mv68KjLwS4KIftEZ7G5UgX+6CAorr3Fy8nq7bpMODYdADKDgcu3048c5UKHho0YzdL1XLOoYwNd6niAMHV+DmL91fIwlJcP1ljb0CfZJnEStKjZwXwpzbS7nbPFlcOQbRNJX7LazpV4zWjPLy4GGGPLdA743lx1Wme4a196A6Ik3J+0ccCUGF0ZjoZRcW4W/5xx23VRLCmauv56CArFyV7uxzuTUKL7+4FygRL/bRfbGcN+YTBXz/FU9XLKW2QdqfelLZ8Ofr+avNR8VeTP7np90LkPsrzYo=
  - secure: IR3cPnZWm5zO8WJava1ILwJvhO7O86yCOAwV3LGun6AhRPwvRjp1QVA88z9QsUJoDoPqAIL1ILjo7nPK5iELtF71ja26xD0mxE5eCVvTPxabMj3bofI55GcHwgDvYKPM02fgXVrQh47sJX6SiImtykd7VqYo2Dg4mfVa6x22Rgae+e6TXyVbdixCcqUxR31DUkc3F1SLx4fOeTCu4N6BcVw19492OxNvJbNkB48W0XHRLDXzRKDk7ETygSNcwC6h/GqV66jtAiwDR1NM/JrOBmWWo82RU2GtGkkOeOPuNDHeA4/cuYkNXBbHKVddvUGElBbqfViDJoCogvKE45O4ZVcLeyi7G3Pb5RsM06cm8RQ7ifIAWKYgbU2MjwEYLNR89tiJzCGI1zhqZxImJvS0nWH1nIvmWa4Cu4ATxCE4gwEB6NW9Vb5bMrRjBK+zwq5ekKdsH2LaqbfsAzYf+76pPvPWdapYiqB9/gkUy2E4GFSu/nTQdJ/jlVGaYdQ1x3CdFkFxzIokoaYnSxNzJxBxUV/e67NyLWuTjufJN4XDzI11g6jm1toRJRo8ktbFSc5VlTIaL8bR/scuJ9XhbUSMnD1+ftaypvy9fIgDT+VX7ONnzbyZY3xAxLp2RA5Mn6dcxyETW7PXB/7p0heKeonJ8leN804xqtZxbi9o9aSv3OM=
  - secure: WbA3H8Qkdi/1HNNWUhev0arXS63Hn/50qGuACP1RPopYcXi2pbrUwtHvQgctKFOI6ev+gsHTWSkoa+x8lr7EFda8ukc25/hPa/emaTInMxxXU/yL7Lx8L67tMtW0Qkc8j2YGYzxMD/yZEpd0xBva3RHhqP8XUgVSZUiw8WzHoD0CKXvplbu1sL5Jl6sZ/PA+xF9+4vz5+GuOYSYhAVzkNdlYOsdGjb0ZmaFA1CGPboITm5t6xZfifRZ6O2LqJA6MlZiMcsYRqwbRUTWDG98cYDHrnupb86+YIc6/zsY6Jso3FDxX6NcwUp0kvAiowYtakVd/NFqHodwxGqND6Nsx0LDhMNWms+lh1yA4d4B8uyfLSKFQ/fUQvuWErX6bh1zC4KtjuigK+uupYmD2QWb8IOqEy3XZzAxTc1n3zWVFI+pQ21OF5lf8lq1HE4u3njl9+xUlur5kvbn9N9VBft7yPR9bX648GuZFWhu/J1kuWQjJSVjgX9cTTWLMf53MbNyjTbiM+cJueOag4FSiPw/t+NL77hUj2w91Ui7wm+tdGSkbK7LZb2MQa2hsd023n9ysqOEi6yCa4Z7ua4LF/JqWYKzqYo9geaNiRH59J7bZJLv+LdeH4TVCqAO/7Phdf9fLHzsGF3tq300a2ytDbZEX2ZGHpxgwG/0JWu2iTEvUZi0=

script:
- ./mvnw clean install -DskipTests

after_success:
- docker login -u $DOCKER_UNAME -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
  fi`
- export IMAGE_NAME=slmnkzm/hrs
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: hrs1
